services:
  haproxy:
    image: try-fastapi-keycloak/haproxy
    build:
      context: ./haproxy
      target: haproxy
      args:
        - VHOST_FQDN=${VHOST_NAME:-test}.test
    networks:
      default:
        aliases:
          - ${VHOST_NAME:-test}.test
    ports:
      - target: 80
        host_ip: 127.0.0.1
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        host_ip: 127.0.0.1
        published: 443
        protocol: tcp
        mode: host
    depends_on:
      - keycloak
      - python
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    volumes:
      - keycloak_data:/opt/keycloak/data:rw
      - ./keycloak/import:/opt/keycloak/data/import:rw
      - ./certs/${VHOST_NAME:-test}.test:/certs:ro
    env_file:
      - keycloak/.env
      - keycloak/.env.local
    # export sample realm
    # command: export --realm sample --dir /opt/keycloak/data/import/ --users same_file
    command: >-
      start-dev
      --import-realm
      --https-certificate-file=/certs/cert.pem
      --https-certificate-key-file=/certs/key.pem
      --http-port=80
      --https-port=443
  python:
    image: ghcr.io/mitarothanken/try-fastapi-keycloak/devcontainers/python-with-java-and-node:20240414-0543
    volumes:
      - .:/workspaces:cached
    environment:
      - VHOST_FQDN=${VHOST_NAME:-test}.test
    command: sleep infinity
volumes:
  keycloak_data:
